# Generated by Django 3.0.6 on 2020-06-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=50)),
                ('Date', models.DateField(blank=True)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=400)),
            ],
        ),
    ]
