# Generated by Django 3.0.6 on 2020-06-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
