# Generated by Django 3.0.6 on 2020-06-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200601_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Description',
            field=models.CharField(max_length=200),
        ),
    ]
