# Generated by Django 3.0.6 on 2020-06-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200601_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=50)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
    ]
